version: 2
updates:
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'daily'
    prefix: '- r '
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    prefix: '. e '
