name: Run tests

on: [push, pull_request,workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.111.0
        run: |
          ruby --version
          bundle install

 
